
export interface BookPage {
  title: string;
  content: string;
}

export interface BookData {
  title: string;
  subtitle: string;
  author: string;
  version: string;
  pages: BookPage[];
}

export const NEURAL_PRISM_BOOK: BookData = {
  title: "The Neural Prism Platform",
  subtitle: "Refracting Super-Intelligence into Human Utility",
  author: "Prism Architect Team",
  version: "v6.5.0-MASTER",
  pages: [
    {
      title: "I. The Refractive Philosophy",
      content: `
# 🌈 Introduction: The Refractive Philosophy

Neural Prism is a fundamental shift in how humans interact with super-intelligent models. While traditional interfaces force users to learn complex prompting, our platform acts as a refractive lens—taking raw, blindingly powerful intelligence from **Google DeepMind's Gemini 3** and splitting it into a beautiful, useful spectrum of domain-specific tools.

## The Spectrum of Utility
As light is split into colors, we split reasoning into actions:
- **Red**: Safety & Emergency Protocols
- **Orange**: Career & Growth
- **Yellow**: Logistics & Daily Errands
- **Green**: Financial Verification
- **Blue**: Software Engineering
- **Indigo**: Architectural Research
- **Violet**: Creative Expression
      `
    },
    {
      title: "II. Heuristic Convergence",
      content: `
# 🧠 Innovation: Heuristic Logic Tracing

Our most disruptive feature is the **Builder Studio Neural IDE**. It replaces heavy server-side compilers with AI-driven simulation.

### The Heuristic Convergence Lemma
The core engine utilizes a probabilistic logic tracer that treats source code as a set of constraints rather than instructions.

$$
\begin{aligned}
\text{Let } \Psi(c) &\text{ be the neural refraction of code } c \\
\text{Given } \epsilon &> 0, \exists N \in \mathbb{N} \text{ such that } \forall n > N: \\
P\left( \| \text{Sim}(c)_n - \text{Nat}(c)_n \| < \epsilon \right) &\geq 1 - \delta \\
\text{Current Benchmark: } 1 - \delta &\approx 0.982
\end{aligned}
$$

By providing the model with a "Digital Twin" system prompt, we instruct it to mentally execute the logic and predict the STDOUT.
      `
    },
    {
      title: "III. Builder Studio: Neural Simulation",
      content: `
# 🏗️ Sector: Builder Studio

The Builder Studio is a sovereign workspace for engineering. Unlike traditional IDEs that require local toolchains or expensive cloud containers, the Prism uses **Neural Simulation**.

### Virtual File System (VFS)
The VFS normalizes files from **GitHub, Google Drive, and local cache**. When you click "Run", the Prism doesn't spin up a Docker container. It initiates a **Heuristic Trace**.

### Socratic Debugging
When the simulation encounters an error, it doesn't just crash. It explains the failure using the **Socratic Method**, asking the developer questions about their logic rather than simply providing a fix.
      `
    },
    {
      title: "IV. The Scribe Protocol",
      content: `
# 📹 Scribe Protocol: Activity Capture

High-fidelity recording is essential for knowledge persistence. The **Neural Scribe** is our advanced activity capture engine.

### Sequential Permission Flow
To ensure 100% reliability of the camera overlay, we implemented a **Sequential Handshake**. The system requests Display Media first, followed immediately by User Media (Camera).

### Canvas Compositor
The recording utilizes an off-screen **Canvas Compositor** that stitches the Screen, Camera (PIP), and System Audio into a single 30FPS stream. This eliminates the "Missing PIP" bug common in standard browser-based recorders.
      `
    },
    {
      title: "V. Finance Lab: Asset Synthesis",
      content: `
# 💳 Sector: Finance Lab (Check Designer)

The Finance Lab demonstrates the Prism's ability to generate **verifiable physical artifacts**.

### Pixel-Perfect Document Assembly
We bypass standard CSS-to-PDF rendering, which often artifacts. Instead, we use **High-DPI Rasterization**. Every check is assembled on a 1800x810 2D canvas, ensuring every micro-line and security feature is preserved.

### Neural Signatures
Your signature is not a static image. It is a **Sovereign Asset** captured in the Signature Pad and synced via the **Web Crypto API**, ensuring that your physical stroke is linked to your digital identity.
      `
    },
    {
      title: "VI. Security Seals & Watermarking",
      content: `
# 🛡️ Anti-Forgery: Security Synthesis

Every financial asset generated by the Prism includes a **Unique Security Seal**.

### Contextual Watermarking
The AI analyzes the check metadata (Memo, Payee, Amount) and synthesizes a unique background pattern. This "Visual DNA" makes every asset difficult to replicate.

### Temporal Liquidity
Using the **Temporal Liquidity Protocol**, assets can be "Locked" to specific offline windows. Claims are verified against the neural ledger, allowing for safe peer-to-peer value exchange without instant internet clearing.
      `
    },
    {
      title: "VII. Neural Assets: The Wallet",
      content: `
# 💰 Sector: Neural Assets (Wallet)

The Wallet manages your **VoiceCoin** ledger. VoiceCoins represent the value of intelligence exchanged within the community.

### Proof of Refraction
Transactions follow a **Handshake Flow**:
1. **Issue**: Sender generates a Digital Receipt.
2. **Escrow**: Funds are moved to a temporary ledger hold.
3. **Claim**: Receiver verifies the receipt and claims the funds.

$$ \text{TransactionValid} \iff \text{Sign}_{User}(\text{Hash}(Data)) = \text{Verified} $$

This ensures all value transfers are intentional and auditable by both nodes.
      `
    },
    {
      title: "VIII. Cryptographic Sovereignty",
      content: `
# 🔑 Decentralized Identity (ECDSA)

The Prism's security model is built on **Total Sovereignty**. 

### On-Device Key Generation
Private keys never touch the cloud. We use the **Web Crypto API** to generate **ECDSA P-256** keys directly in your browser.

### The Trust Certificate
When you register, the Prism issues a **Public Certificate**. This certificate is used by the Global Ledger to verify your signed transactions without ever knowing your private key. You own your identity; we only verify your signatures.
      `
    },
    {
      title: "IX. Career Hub: Multimodal Eval",
      content: `
# 🎓 Sector: Career Hub

The Career Hub uses **Multimodal Interrogation** to prepare candidates for high-level technical roles.

### Multimodal Interrogation
The interviewer persona doesn't just read your chat; it **hears** your voice and **sees** your code in real-time. It evaluates:
- **Logical Purity**: The correctness and complexity of your code.
- **Articulation**: How clearly you explain your reasoning.
- **Presence**: Analyzing visual cues to provide feedback on confidence and body language.
      `
    },
    {
      title: "X. Socratic Feedback Logic",
      content: `
# 🧪 Socratic Evaluation & Scoring

After every interview, the Prism synthesizes a **Neural Evaluation Report**.

### Dynamic Scoring Matrix
The AI grades you across three vectors:
1. **Technical Skills** (The Blue Refraction)
2. **Communication** (The Pink Refraction)
3. **Collaboration** (The Emerald Refraction)

It generates **Optimized STAR Stories** based on your performance, providing you with a "Perfect Version" of your own experiences to use in real interviews.
      `
    },
    {
      title: "XI. Activity Hub: Voice Cast",
      content: `
# 🎙️ Sector: Activity Hub (Discovery)

The Activity Hub is the "Registry of Knowledge". It replaces static learning with **Interactive Lectures**.

### The Socratic Dialogue Pattern
When you select a lesson, the system refracts the content into a two-person dialogue (Teacher vs Student). This mimics the classic educational style used for centuries, making complex topics naturally digestible.

### Live Participation
At any point, you can click "Start Live Chat" to enter the dialogue. The host persona recognizes the current context and shifts from lecture mode to peer-collaboration mode.
      `
    },
    {
      title: "XII. Curriculum Synthesis",
      content: `
# 📜 Automating Education

Building a custom curriculum in the Prism is an **Active Refraction**.

### Ingest & Refract
You can provide a raw URL (PDF, documentation) and the **Magic Creator** will:
1. Parse the structure.
2. Synthesize a 10-chapter learning path.
3. Generate boilerplate code for every technical lesson.

Knowledge moves too fast for books. The Prism ensures your learning material is as current as the source documentation.
      `
    },
    {
      title: "XIII. Observability: The Matrix",
      content: `
# 🐞 Observability: Diagnostic Matrix

Maintaining a multi-model real-time system requires deep visibility.

### Throttled Neural Log Buffer
Standard logging can lag the UI during high-frequency AI turns. Our console uses a **Throttled Log Buffer** that batches handshake metadata and terminal traces, updating the UI at 800ms intervals to preserve frame-rate integrity.

### Raw Trace Access
Architects can access the **Raw JSON Trace** of every Gemini handshake, allowing for sub-second debugging of logic-drift or connectivity faults.
      `
    },
    {
      title: "XIV. Feedback Refraction",
      content: `
# 🔄 The Self-Enhancement Loop

The Prism doesn't just collect bugs; it **refracts them into context**.

### Trace Bundling
When you submit feedback, the system performs a **Trace Bundle**. It attaches the last 20 log entries—including specific model instructions and errors—to your message. 

This provides the engineering team with the "Raw Neural Context" needed to perform recursive logic refinement on the system prompts.
      `
    },
    {
      title: "XV. Scripture: Acoustic Archeology",
      content: `
# 📜 Sector: Scripture Sanctuary

The Scripture Sanctuary uses **Acoustic Archeology** to reconstruct ancient wisdom.

### Bilingual Archiving
We store verses in dual-language nodes, allowing for simultaneous cross-reference.

### Neural Re-voicing
The Sanctuary uses specialized "Historical Timbre" models (Puck, Fenrir, Kore) to read texts in a way that evokes the weight of history. Each verse is an individual ledger node, capable of being independently verified and cached.
      `
    },
    {
      title: "XVI. Visual Canvas: Vector CRDTs",
      content: `
# 🎨 Sector: Visual Canvas (Whiteboard)

Collaborative sketching in the Prism is powered by **Vector CRDTs** (Conflict-free Replicated Data Types).

### Real-Time Synthesis
When multiple members sketch on the infinite whiteboard, the Prism uses a deterministic timestamping algorithm to ensure that all strokes are merged without data loss.

### Heuristic Sketching
The AI can "read" your sketches. If you draw a rough diagram of a database, the AI can refract that drawing into a functional SQL schema or a PlantUML architecture string.
      `
    },
    {
      title: "XVII. Hardware: OCI Acceleron",
      content: `
# 🌩️ Infrastructure: The OCI Layer

Neural Prism relies on **Oracle Cloud Infrastructure (OCI)** for high-intensity neural processing.

### Dedicated AI Fabric
We leverage the **Acceleron Fabric** to ensure that our real-time voice sessions have deterministic latency. 

$$ \text{Latency}_{P99} < 1.2\mu\text{s} $$

This hardware grounding allows us to stream 30FPS video frames and real-time audio without the "jitter" common in traditional cloud networking.
      `
    },
    {
      title: "XVIII. Gift Workshop: Synthesis",
      content: `
# 🎁 Sector: Gift Workshop

The Gift Workshop is our most "Violet" (Creative) refraction. It combines image, text, and audio synthesis into a single artifact.

### Multimodal Gifting
1. **Visual**: AI-generated cover art based on your unique wish.
2. **Auditory**: Custom music and neural voice greetings.
3. **Sentiment**: Heartfelt messages expanded from simple user drafts.

These assets are bundled into a portable **ZIP Package** for digital or physical delivery.
      `
    },
    {
      title: "XIX. Sovereign Storage Model",
      content: `
# ☁️ The Sovereign Bridge

Neural Prism is a **Temporary Lens**, not a data trap.

### Your Drive, Your Data
Everything you create—source code, PDFs, check records, and recordings—is synced directly to your **Personal Google Drive**. We store the metadata, but you own the artifacts.

### IndexedDB Cache
For performance, we utilize a local "Prism Cache" (IndexedDB) to store heavy audio fragments. This ensures sub-100ms playback even when the network is unstable.
      `
    },
    {
      title: "XX. Preemptive Rotation",
      content: `
# 🧠 Link Resilience: Neural Rotation

Maintaining long-running voice sessions (like 45-minute interviews) is technically challenging due to model timeouts.

### Silent Handover
We implemented a **Preemptive Rotation** protocol. Every 5 minutes, the system silently initiates a new WebSocket connection, passing the "Context Snapshot" from the previous session to the next. The user experiences zero interruption in the dialogue.
      `
    },
    {
      title: "XXI. Identity & Metadata",
      content: `
# 🆔 The Neural Fingerprint

Every artifact in the Prism is stamped with a **Neural Fingerprint**.

### Deterministic UUIDs
We use 256-bit entropy to generate 44-character secure IDs. These IDs serve as the "Sovereign Link" between your local cache, the global ledger, and your Google Drive.

### Verification Matrix
Scanning the QR code on any Prism-generated document (Check, Label, Book) allows a third party to verify its authenticity against the public ledger record.
      `
    },
    {
      title: "XXII. The 30-Day Refraction",
      content: `
# ⏱️ The Creation Story: Vibe Coding

This entire platform—comprising over **30,000 lines of generated code**—was built by a single engineer in approximately 30 days.

### Recursive Engineering
High-fidelity AI software is not typed; it is *orchestrated* through resilient human-AI feedback loops. We utilized a "Refraction" strategy: constant feedback and snapshot restores to battle neural drift during high-frequency development sessions. 
      `
    },
    {
      title: "XXIII. Roadmap to v7.0",
      content: `
# 🚀 Future: Federated Refraction

The current Prism is curated. v7.0 will move toward **Decentralized Refraction**.

### Community Refractions
Members will be able to define their own "Activity Refractions", creating an infinite library of custom AI tools. 

### Autonomous Refactoring
The system will begin monitoring its own diagnostic logs to suggest architectural improvements, creating a truly self-evolving Intelligence Hub.
      `
    },
    {
      title: "XXIV. Final Handshake",
      content: `
# 🤝 Conclusion: Built for Humanity

The Neural Prism is the final bridge between superhuman AI capacity and daily human utility. 

We make complexity invisible and intelligence colorful. We believe AI should be an extension of the human soul—a spectrum of tools that empower you to build, learn, and grow every single day.

---
**Neural Prism Platform v6.5.0**
*Refracted by Intelligence. Built for Humanity.*
      `
    }
  ]
};
